
import Navbar from "@/components/navbar";
import "../styles/global.css"
import "../styles/index.css"
import { AppProvider, useUser } from "@/context/context";

export const metadata = {
   
  title: {
    default:"Bloggy website  homepage",
    template:"%s | Bloggy Website"
  },
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Navbar/>                
            {children}
        </AppProvider>
      </body>
    </html>
  );
}
