
import Navbar from "@/components/navbar";
import "../styles/global.css"
import "../styles/index.css"
import { AppProvider } from "@/context/context";
import {Inter} from "next/font/google"
// Load the font
const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700'], // Optional: choose weights you use
  display: 'swap',        // Optional: better CLS
});


export const metadata = {
   
  title: {
    default:"Bloggy website  homepage",
    template:"%s | Bloggy Website"
  },
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <Navbar/>                
            {children}
        </AppProvider>
      </body>
    </html>
  );
}
